
server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: orange-bank
  datasource:
    url: jdbc:mysql://localhost:3306/orange?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
